<?php

declare(strict_types=1);

namespace Honey\ODM\Core\Tests\Implementation\Examples;

use Honey\ODM\Core\Config\AsDocument;
use Honey\ODM\Core\Config\AsField;

/**
 * A document whose id is unknown until it is persisted - typically generated by a PrePersistEvent listener.
 */
#[AsDocument(collection: 'generated')]
final class TestDocumentWithGeneratedId
{
    #[AsField(primary: true)]
    public ?string $id = null;

    public function __construct(
        #[AsField]
        public string $name,
    ) {
    }
}
